export const SET_SINGER = 'SET_SINGER'
export const SET_PLAYING = 'SET_PLAYING'
export const SET_FULLSRCEEN = 'SET_FULLSRCEEN'
export const SET_PLAYLIST = 'SET_PLAYLIST'
export const SET_ORDERPLAYLIST = 'SET_ORDERPLAYLIST'
export const SET_MODE = 'SET_MODE'
export const SET_CURRENTINDEX = 'SET_CURRENTINDEX'

